// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NZHIapGs7KqwbHA1sgP0dDL72pyRBao',
    appId: '1:821524877394:web:6b003badcce8a6945ccf8b',
    messagingSenderId: '821524877394',
    projectId: 'new-app-firebase-75bda',
    authDomain: 'new-app-firebase-75bda.firebaseapp.com',
    storageBucket: 'new-app-firebase-75bda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbLHJCymoDGmZWNR2fC44bUi40B3Z8nqA',
    appId: '1:821524877394:android:ac5789acf54370905ccf8b',
    messagingSenderId: '821524877394',
    projectId: 'new-app-firebase-75bda',
    storageBucket: 'new-app-firebase-75bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbj5MRCTZ2c3O93kiN1ii2KYuzUxLgMs',
    appId: '1:821524877394:ios:e14015ad9604b66a5ccf8b',
    messagingSenderId: '821524877394',
    projectId: 'new-app-firebase-75bda',
    storageBucket: 'new-app-firebase-75bda.appspot.com',
    iosClientId: '821524877394-jo2ps42dk1bckoi0nbm82j9ipno931jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfbj5MRCTZ2c3O93kiN1ii2KYuzUxLgMs',
    appId: '1:821524877394:ios:e14015ad9604b66a5ccf8b',
    messagingSenderId: '821524877394',
    projectId: 'new-app-firebase-75bda',
    storageBucket: 'new-app-firebase-75bda.appspot.com',
    iosClientId: '821524877394-jo2ps42dk1bckoi0nbm82j9ipno931jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newappfirebase',
  );
}
